# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-18 20:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessedImg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.FilePathField(verbose_name='/home/fix_this')),
                ('finish_date', models.DateField(auto_now_add=True)),
                ('finish_time', models.TimeField(auto_now_add=True)),
                ('processor_usage', models.DurationField()),
                ('score', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
        ),
        migrations.CreateModel(
            name='UnprocessedImg',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('path', models.FilePathField(verbose_name='/home/fix_this')),
                ('receive_date', models.DateField(auto_now_add=True)),
                ('receive_time', models.TimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='processedimg',
            name='unprocessed_img',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='imgapp.UnprocessedImg'),
        ),
    ]
