# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-18 23:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imgapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='processedimg',
            name='key_path',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='unprocessedimg',
            name='processed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='unprocessedimg',
            name='serial',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='processedimg',
            name='path',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='unprocessedimg',
            name='path',
            field=models.CharField(default='', max_length=100),
        ),
    ]
